- name: ensure libvirt and other deps are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - qemu-kvm
    - libvirt
    - libvirt-python
    - python-lxml
    - libguestfs-tools
  become: true

- include: configure_kvm.yml

- name: start libvirtd
  service:
    name: libvirtd
    state: running
    enabled: true
  become: true
