release: mitaka
undercloud_image_url: https://images.rdoproject.org/mitaka/cbs/cloudsig-stable/stable/undercloud.qcow2
overcloud_image_url: https://images.rdoproject.org/mitaka/cbs/cloudsig-stable/stable/overcloud-full.tar
ipa_image_url: https://images.rdoproject.org/mitaka/cbs/cloudsig-stable/stable/ironic-python-agent.tar
