artifacts:
  - undercloud.qcow2
  - undercloud.qcow2.md5
  - ironic-python-agent.tar
  - ironic-python-agent.tar.md5
  - overcloud-full.tar
  - overcloud-full.tar.md5
release: mitaka
build_system: delorean
publish: false