default_disk: 50

undercloud_memory: 16384
undercloud_vcpu: 4

control_memory: 8192
compute_memory: 8192

overcloud_nodes:
  - name: control_0
    flavor: control
  - name: compute_0
    flavor: compute