---
- name: Add virthost to inventory
  hosts: localhost
  gather_facts: no
  vars:
    # This allows running ansible in a virtualenv,
    # while using python from the base install
    ansible_python_interpreter: "/usr/bin/python"
  roles:
    - provision/manual
    - rebuild-inventory

- name:  Setup undercloud and baremetal vms and networks in libvirt
  hosts: host0
  gather_facts: yes
  roles:
    - libvirt/setup

- name: Rebuild inventory
  hosts: localhost
  gather_facts: no
  vars:
    # This allows running ansible in a virtualenv,
    # while using python from the base install
    ansible_python_interpreter: "/usr/bin/python"
  roles:
    - rebuild-inventory

- name:  Install undercloud and deploy overcloud
  hosts: undercloud
  gather_facts: no
  vars:
    extra_args: "--control-scale 3 -e /usr/share/openstack-tripleo-heat-templates/environments/puppet-pacemaker.yaml --ntp-server pool.ntp.org"
    tempest: false
    introspect: false
    pingtest: true
  roles:
    - overcloud