control_memory: 6144
compute_memory: 4096

undercloud_memory: 8192
undercloud_vcpu: 2

overcloud_nodes:
  - name: control_0
    flavor: control
  - name: control_1
    flavor: control
  - name: control_2
    flavor: control

  - name: compute_0
    flavor: compute

introspect: false

extra_args: "--control-scale 3 -e /usr/share/openstack-tripleo-heat-templates/environments/puppet-pacemaker.yaml --ntp-server pool.ntp.org"
tempest: false
pingtest: true