# Deploy an Openstack environment with a containerized overcloud
# using scenario004

undercloud_setup: true
network_isolation: false
enable_pacemaker: false
overcloud_ipv6: false

containerized_overcloud: true
# Undercloud registry mirror
undercloud_docker_registry_mirror: "{{ lookup('env','NODEPOOL_DOCKER_REGISTRY_PROXY') }}"
undercloud_generate_service_certificate: false

ssl_overcloud: false

tempest_config: false
# TODO(emilien)
# glance+swift+ceph-rgw doesn't work yet but we're investigating/
# should be fixed soon
test_ping: false
run_tempest: false
step_introspect: false

deploy_composable_scenario: true
composable_scenario: scenario004-multinode-containers.yaml
validate_template: scenario004-multinode.yaml

# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate
composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant
