undercloud_generate_service_certificate: false
enable_opstools_repo: true
test_ping: true

# This enables the run of several tripleo-validations tests through Mistral
run_tripleo_validations: True
# This enables the run of tripleo-validations negative tests through shell
# scripts
run_tripleo_validations_negative_tests: True
# Exit tripleo-quickstart on validations failure
exit_on_validations_failure: False

deploy_composable_scenario: true
composable_scenario: scenario001-multinode.yaml
validate_template: scenario001-multinode.yaml
