undercloud_generate_service_certificate: false
enable_opstools_repo: true

# Use the traditional ping test in newton and ocata
# Run tempest in pike+

test_ping: >-
  {% if release in ['newton', 'ocata'] -%}
  true
  {%- else -%}
  # TODO(emilien) change it to false when:
  # - https://review.openstack.org/#/c/490376 is merged
  # - https://bugs.launchpad.net/tripleo/+bug/1708793 is fixed
  true
  {%- endif -%}

tempest_config: >-
  {% if release in ['newton', 'ocata'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}

run_tempest: >-
  {% if release in ['newton', 'ocata'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}

validate_template: scenario001-multinode.yaml

# https://review.openstack.org/#/c/490376 should get us more coverage than we had before
# with pingtest. Remove this comment once 490376 is merged.
test_regex: 'tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_volume_boot_pattern'

# This enables the run of several tripleo-validations tests through Mistral
run_tripleo_validations: True
# This enables the run of tripleo-validations negative tests through shell
# scripts
run_tripleo_validations_negative_tests: True
# Exit tripleo-quickstart on validations failure
exit_on_validations_failure: False

deploy_composable_scenario: true
composable_scenario: scenario001-multinode.yaml
