# Summary of the feature set.
# Deploy an Openstack environment with a non-containerized overcloud,
# and upgrade it to a containerized overcloud.

undercloud_setup: true
network_isolation: false
enable_pacemaker: false
overcloud_ipv6: false

containerized_overcloud: true

undercloud_generate_service_certificate: false

ssl_overcloud: false

tempest_config: false
# TODO: enable pingtest when the job passes with some time left
# before the time limit
test_ping: false
run_tempest: false
step_introspect: false

composable_scenario: scenario002-multinode-containers.yaml

# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate
