# Deploy an Openstack environment with a containerized overcloud
# using scenario001

undercloud_setup: true
network_isolation: false
enable_pacemaker: false
overcloud_ipv6: false

enable_opstools_repo: true

containerized_overcloud: true
undercloud_generate_service_certificate: false

ssl_overcloud: false

tempest_config: false
test_ping: true
run_tempest: false
step_introspect: false

deploy_composable_scenario: true
composable_scenario: scenario001-multinode-containers.yaml
validate_template: scenario001-multinode.yaml

# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate
composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant
