# This config deploys a minimal configuration but with pacemaker to
# simulate a configuration close to HA without requiring 3 controllers

# Define a controller node, a compute node, and a ceph node.
overcloud_nodes:
  - name: control_0
    flavor: control
    virtualbmc_port: 6230

  - name: compute_0
    flavor: compute
    virtualbmc_port: 6231

# Tell tripleo how we want things done.
extra_args: >-
  --ntp-server pool.ntp.org

network_isolation: true
test_ping: true
enable_pacemaker: true
run_tempest: false
