- name: Create repo setup script
  template:
    src: "{{ repo_setup_script }}"
    dest: "{{ repo_setup_dir }}/repo_setup.sh"
    mode: 0755

- include: setup_repos.yml
  static: no
  when: repo_run_live|bool

- include: inject_repos_into_image.yml
  static: no
  when: repo_inject_image_path is defined
