- name: Create packaging script
  template:
    src: "{{ packaging_script }}"
    dest: "{{ working_dir }}"
    mode: 0744

- name: Run the packaging script
  shell: "{{ working_dir }}/{{ packaging_script }}"