- name:  Setup undercloud and baremetal vms and networks in libvirt
  hosts: host0
  gather_facts: yes

  vars:
    url: "http://artifacts.ci.centos.org/artifacts/rdo/images/liberty/delorean/testing/undercloud.qcow2"
    local_working_dir: "{{ lookup('env', 'WORKSPACE') }}/khaleesi"

    default_disk: 50

    undercloud_memory: 16384

    control_memory: 8192
    compute_memory: 8192

    overcloud_nodes:
      - name: control_0
        flavor: control
      - name: compute_0
        flavor: compute
  roles:
    - libvirt/setup

- name: Rebuild inventory
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python"
    local_working_dir: "{{ lookup('env', 'WORKSPACE') }}/khaleesi"
  roles:
    - rebuild-inventory

- name:  Install undercloud and deploy overcloud
  hosts: undercloud
  gather_facts: no
  vars:
    bash_deploy_ramdisk: true
    local_working_dir: "{{ lookup('env', 'WORKSPACE') }}/khaleesi"

    # We need the node definitions here, too, because they are 
    # used to set up flavors.
    default_disk: 50

    undercloud_memory: 16384

    control_memory: 8192
    compute_memory: 8192

    overcloud_nodes:
      - name: control_0
        flavor: control
      - name: compute_0
        flavor: compute
  roles:
    - overcloud
