---
- name: Create the injection script
  template:
    src: inject_gating_repo.sh.j2
    dest: "{{ working_dir }}/inject_gating_repo.sh"

- name: Inject the gating repo
  command: >
    virt-customize -a {{ working_dir }}/undercloud.qcow2
    --upload {{ compressed_gating_repo }}:/tmp/gating_repo.tar.gz
    --run '{{ working_dir }}/inject_gating_repo.sh'
    --update
  environment:
    LIBGUESTFS_BACKEND: direct
    LIBVIRT_DEFAULT_URI: "{{ libvirt_uri }}"
