- name:  Setup undercloud and baremetal vms and networks in libvirt
  hosts: host0
  gather_facts: no
  vars:
    url: "http://artifacts.ci.centos.org/artifacts/rdo/images/liberty/cbs/testing/undercloud.qcow2"
    local_working_dir: "{{ lookup('env', 'WORKSPACE') }}"
    vms:
      engine: 'kvm'
      undercloud:
        nodes:
          - name: undercloud
            disk_size: '50'
            memory: '16384'
            cpus: '4'
        arch: 'x86_64'
        bootdev: 'hd'
      overcloud:
        arch: 'x86_64'
        bootdev: 'network'
        nodes:
          - name: control
            disk_size: '50'
            memory: '8192'
            cpus: '2'
            profile: control
          - name: compute
            disk_size: '50'
            memory: '8192'
            cpus: '2'
            profile: compute
          - name: ceph
            disk_size: '50'
            memory: '4096'
            cpus: '1'
            profile: ceph
      volume_path: /var/lib/libvirt/images/
      volume_pool: default
      diskbus: 'sata'
  roles:
    - libvirt/setup

- name: Rebuild inventory
  hosts: localhost
  gather_facts: no
  roles:
    - rebuild-inventory

- name:  Install undercloud and deploy overcloud
  hosts: undercloud
  gather_facts: no
  vars:
    ceph_args: "--ceph-storage-scale 1 --ceph-storage-flavor ceph"
    local_working_dir: "{{ lookup('env', 'WORKSPACE') }}"
  roles:
    - overcloud