release: master
dlrn_hash: current-tripleo
undercloud_image_url: http://artifacts.ci.centos.org/artifacts/rdo/images/master/delorean/current-tripleo/stable/undercloud.qcow2
overcloud_image_url: http://artifacts.ci.centos.org/artifacts/rdo/images/master/delorean/current-tripleo/stable/overcloud-full.tar
ipa_image_url: http://artifacts.ci.centos.org/artifacts/rdo/images/master/delorean/current-tripleo/stable/ironic-python-agent.tar
repos:
  - type: generic
    reponame: delorean
    filename: delorean.repo
    baseurl: https://trunk.rdoproject.org/centos7-master/{{ dlrn_hash }}/
    priority: 20

  - type: file
    filename: delorean-deps.repo
    down_url: http://trunk.rdoproject.org/centos7-master/delorean-deps.repo

  - type: package
    pkg_name: centos-release-ceph-jewel
    custom_cmd: 'sudo yum install -y --enablerepo=extras'

repo_cmd_after: |
  sudo yum-config-manager --save --setopt centos-ceph-jewel.gpgcheck=0
  sudo yum repolist;
  sudo yum update -y

