release: mitaka
undercloud_image_url: http://artifacts.ci.centos.org/artifacts/rdo/images/mitaka/delorean/consistent/stable/undercloud.qcow2
overcloud_image_url: http://artifacts.ci.centos.org/artifacts/rdo/images/mitaka/delorean/consistent/stable/overcloud-full.tar
ipa_image_url: http://artifacts.ci.centos.org/artifacts/rdo/images/mitaka/delorean/consistent/stable/ironic-python-agent.tar
