release: mitaka
undercloud_image_url: http://artifacts.ci.centos.org/artifacts/rdo/images/mitaka/cbs/cloudsig-testing/testing/undercloud.qcow2
overcloud_image_url: http://artifacts.ci.centos.org/artifacts/rdo/images/mitaka/cbs/cloudsig-testing/testing/overcloud-full.tar
ipa_image_url: http://artifacts.ci.centos.org/artifacts/rdo/images/mitaka/cbs/cloudsig-testing/testing/ironic-python-agent.tar

