release: pike
dlrn_hash: current-tripleo
overcloud_image_url: https://images.rdoproject.org/{{ release }}/rdo_trunk/{{ dlrn_hash }}/overcloud-full.tar
ipa_image_url: https://images.rdoproject.org/{{ release }}/rdo_trunk/{{ dlrn_hash }}/ipa_images.tar
overcloud_as_undercloud: true
repos:
  - type: generic
    reponame: delorean
    filename: delorean.repo
    baseurl: https://trunk.rdoproject.org/centos7-{{ release }}/{{ dlrn_hash }}/
    priority: 20

  - type: file
    filename: delorean-deps.repo
    down_url: http://trunk.rdoproject.org/centos7-{{ release }}/delorean-deps.repo

  - type: package
    pkg_name: centos-release-ceph-jewel
    custom_cmd: 'sudo yum install -y --enablerepo=extras'

repo_cmd_after: |
  sudo yum-config-manager --save --setopt centos-ceph-jewel.gpgcheck=0
  sudo yum repolist;
  sudo yum update -y
