---
- name: remove virt_power_key
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ virt_power_key }}"
    - "{{ virt_power_key }}.pub"

- name: delete non-root user
  user:
    name: "{{ non_root_user }}"
    state: absent
    remove: yes

- name: remove non-root user passwordless sudo priveledges
  file:
    name: "/etc/sudoers.d/{{ non_root_user }}"
    state: absent
