- name: generate convert script
  template:
    src: convert_image.sh.j2
    dest: "{{ convert_image_working_dir}}/convert_image.sh"

- name: copy overcloud-full.qcow2 to undercloud.qcow2
  command: >
    cp {{ convert_image_working_dir}}/overcloud-full.qcow2
       {{ convert_image_working_dir}}/undercloud.qcow2
  changed_when: true

# Resize the undercloud image using qemu-img resize
- name: Resize the undercloud image using qemu-image resize
  command: >
    qemu-img resize {{ convert_image_working_dir }}/undercloud.qcow2
                    {{ flavors[undercloud_node.name].disk }}G
  changed_when: true

- name: convert image
  command: >
    virt-customize -v --smp 2 -m 4096
    -a {{ convert_image_working_dir }}/undercloud.qcow2
    --run convert_image.sh
  changed_when: true
  args:
    chdir: "{{ convert_image_working_dir }}"
  environment:
    LIBGUESTFS_BACKEND: direct
    LIBVIRT_DEFAULT_URI: "{{ libvirt_uri }}"

