- name: Ensure local working dir exists
  delegate_to: localhost
  file:
    path: "{{ local_working_dir }}"
    state: directory

- name: rebuild-inventory
  template:
    dest: "{{ local_working_dir }}/hosts"
    src: inventory.j2
