# Grab CPU flags from "/proc/cpuinfo" and put the result into the
# "cpu_flags_cmd" variable.
- name: Get cpu flags
  command: |
    awk -F: '/^flags/ {print $2; exit}' /proc/cpuinfo
  register: cpu_flags_cmd
  changed_when: false

# Extract the flags into a list variable named "cpu_flags".
- name: Set cpu flags fact
  set_fact:
    cpu_flags: "{{ cpu_flags_cmd.stdout.split() }}"

- block:
    - name: Unload kvm_intel module
      modprobe:
        name: "kvm_intel"
        state: "absent"
      become: true

    - name: Configure KVM module with Intel nested virtualization support
      copy:
        dest: "/etc/modprobe.d/kvm_intel.conf"
        content: |
          options kvm_intel nested=1
      become: true

    - name: Re-load kvm_intel module
      modprobe:
        name: "kvm_intel"
        state: "present"
      become: true

    - name: Ensure nested virtualization is enabled
      command: cat /sys/module/kvm_intel/parameters/nested
      register: nested_virtualization
      failed_when: ('FAILED' in nested_virtualization.stderr) or
                   ('N' in nested_virtualization.stdout)
  always:
    - debug:
        msg: >
          /sys/module/kvm_intel/parameters/nested:
          {{ nested_virtualization.stdout }}
  when:
    - "{{ 'Intel' in ansible_processor |join('') }}"
    - "{{ 'vmx' in cpu_flags }}"

- block:
    - name: Unload kvm_amd module
      modprobe:
        name: "kvm_amd"
        state: "absent"
      become: true

    - name: Configure KVM module with AMD nested virtualization support
      copy:
        dest: "/etc/modprobe.d/kvm_amd.conf"
        content: |
          options kvm_amd nested=1
      become: true

    - name: Re-load kvm_amd module
      modprobe:
        name: "kvm_amd"
        state: "present"
      register: nested_virtualization
      become: true

    - name: Ensure nested virtualization is enabled
      command: cat /sys/module/kvm_amd/parameters/nested
      register: nested_virtualization
      failed_when: ('FAILED' in nested_virtualization.stderr) or
                   ('0' in nested_virtualization.stdout)
  always:
    - debug:
        msg: >
          /sys/module/kvm_amd/parameters/nested:
          {{ nested_virtualization.stdout }}
  when:
    - "{{ 'AMD' in ansible_processor |join('') }}"
    - "{{ 'svm' in cpu_flags }}"
