# WORKAROUND for CentOS virthosts
# The iPXE ROMs shipped with CentOS are too old to work with Ironic.
# RHEL BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1267030
- name: Install newer iPXE ROM on CentOS
  when: ansible_distribution == 'CentOS'
  package:
    name: "http://buildlogs.centos.org/centos/7/cloud/x86_64/openstack-newton/common/ipxe-roms-qemu-20160127-1.git6366fa7a.el7.noarch.rpm"
    state: present
  become: true

# Install the packages required for our desired libvirt environment.
# We store the list of packages in `libvirt_packages` so that in
# theory we can support multiple distributions simply by passing in a
# different list of packages.
- name: Install packages for libvirt
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ libvirt_packages }}"
  become: true

- name: Start libvirtd
  service:
    name: "{{ libvirtd_service }}"
    state: running
    enabled: true
  become: true
