devmode: true
overcloud_as_undercloud: true
images:
    - name: overcloud-full
      url: "{{ overcloud_image_url }}"
      type: tar
    - name: ipa_images
      url: "{{ ipa_image_url }}"
      type: tar
inject_images:
    - "ironic-python-agent.initramfs"
    - "ironic-python-agent.vmlinuz"
    - "ironic-python-agent.kernel"
    - "overcloud-full.qcow2"
    - "overcloud-full.initrd"
    - "overcloud-full.vmlinuz"
release: mitaka
overcloud_image_url: http://66.187.229.139/builds-mitaka/current-tripleo-mitaka/overcloud-full.tar
ipa_image_url: http://66.187.229.139/builds-mitaka/current-tripleo-mitaka/ipa_images.tar
repo_cmd_before: |
  sudo yum install -y yum-plugin-priorities;
  sudo yum clean all;
  sudo rm -rf /etc/yum.repos.d/delorean*;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
  if [[ -e /etc/nodepool/provider ]]; then
  source /etc/nodepool/provider;
  export NODEPOOL_MIRROR_HOST=$(echo "mirror.$NODEPOOL_REGION.$NODEPOOL_CLOUD.openstack.org" | tr '[:upper:]' '[:lower:]');
  fi
repos:
  - type: file
    filename: delorean.repo
    down_url: https://trunk.rdoproject.org/centos7-mitaka/current/delorean.repo
    hash_url: https://trunk.rdoproject.org/centos7-mitaka/current/delorean.repo

  - type: file
    filename: delorean-deps.repo
    down_url: https://trunk.rdoproject.org/centos7-mitaka/delorean-deps.repo

  - type: package
    pkg_name: centos-release-ceph-hammer
    custom_cmd: 'sudo yum install -y --enablerepo=extras'

  - type: generic
    reponame: centos-opstools
    filename: centos-opstools.repo
    baseurl: https://buildlogs.centos.org/centos/7/opstools/x86_64/

repo_cmd_after: |
  {% if not enable_opstools_repo|default(false)|bool %}sudo yum-config-manager --save --setopt centos-opstools.enable=0;
  {%endif %}
  sudo yum-config-manager --save --setopt centos-ceph-hammer.gpgcheck=0;
  if [[ -n "${NODEPOOL_MIRROR_HOST:-''}" ]]; then
  sudo yum remove -y centos-release-ceph-hammer;
  sudo yum-config-manager --add-repo "http://${NODEPOOL_MIRROR_HOST}/centos/7/storage/x86_64/ceph-hammer/";
  echo "gpgcheck=0" >> /etc/yum.repos.d/${NODEPOOL_MIRROR_HOST}*;
  fi
  sudo rpm -e epel-release || true;
  sudo yum remove -y rdo-release || true;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
  sudo yum repolist;
  sudo yum update -y
