devmode: true
overcloud_as_undercloud: true
use_specific_hash: true
docker_registry_host: trunk.registry.rdoproject.org
docker_registry_namespace: newton
delorean_hash_label: &promotion-testing-tag tripleo-ci-testing
docker_image_tag: *promotion-testing-tag


images:
    - name: overcloud-full
      url: "{{ overcloud_image_url }}"
      type: tar
    - name: ipa_images
      url: "{{ ipa_image_url }}"
      type: tar
inject_images:
    - "ironic-python-agent.initramfs"
    - "ironic-python-agent.vmlinuz"
    - "ironic-python-agent.kernel"
    - "overcloud-full.qcow2"
    - "overcloud-full.initrd"
    - "overcloud-full.vmlinuz"
release: newton
overcloud_image_url: https://images.rdoproject.org/newton/delorean/tripleo-upstream/testing/overcloud-full.tar
ipa_image_url: https://images.rdoproject.org/newton/delorean/tripleo-upstream/testing/ipa_images.tar
repo_cmd_before: |
  sudo yum install -y yum-plugin-priorities;
  sudo yum clean all;
  sudo yum-config-manager --disable "*"
  sudo rm -rf /etc/yum.repos.d/delorean*;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
  if [ -e /etc/ci/mirror_info.sh ]; then
    source /etc/ci/mirror_info.sh
  else
    # Otherwise, fallback to official mirrors provided by CentOS.
    export NODEPOOL_CENTOS_MIRROR=http://mirror.centos.org/centos
    export NODEPOOL_BUILDLOGS_CENTOS_PROXY=https://buildlogs.centos.org
    export NODEPOOL_RDO_PROXY=https://trunk.rdoproject.org
  fi
  rdo_dlrn=`curl --silent ${NODEPOOL_RDO_PROXY}/centos7-newton/tripleo-ci-testing/delorean.repo | grep baseurl | cut -d= -f2`
  rdo_dlrn_deps=`curl --silent ${NODEPOOL_RDO_PROXY}/centos7-newton/delorean-deps.repo | grep baseurl | cut -d= -f2`
  if [[ -z "$rdo_dlrn" || -z "$rdo_dlrn_deps" ]]; then
    echo "Failed to parse dlrn hash"
    exit 1
  fi
  export RDO_DLRN_REPO=${rdo_dlrn/https:\/\/trunk.rdoproject.org/$NODEPOOL_RDO_PROXY}
  export RDO_DLRN_DEPS_REPO=${rdo_dlrn_deps/https:\/\/trunk.rdoproject.org/$NODEPOOL_RDO_PROXY}

repos:
  - type: generic
    reponame: delorean
    filename: delorean.repo
    baseurl: $RDO_DLRN_REPO

  - type: generic
    reponame: delorean-deps
    filename: delorean-deps.repo
    baseurl: $RDO_DLRN_DEPS_REPO

  - type: generic
    reponame: centos-qemu
    filename: centos-qemu.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/7/virt/x86_64/kvm-common/

  - type: generic
    reponame: centos-ceph-jewel
    filename: centos-ceph-jewel.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/7/storage/x86_64/ceph-jewel/

  - type: generic
    reponame: centos-opstools
    filename: centos-opstools.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/7/opstools/x86_64/

repo_cmd_after: |
  {% if not enable_opstools_repo|default(false)|bool %}sudo yum-config-manager --save --setopt centos-opstools.enable=0;
  {%endif %}
  sudo yum-config-manager --disable rdo-qemu-ev;
  sudo rpm -e epel-release || true;
  sudo yum remove -y rdo-release centos-release-ceph-* centos-release-openstack-* || true;
  sudo rm -rf /etc/yum.repos.d/CentOS-OpenStack-*.repo /etc/yum.repos.d/CentOS-Ceph-*.repo /etc/yum.repos.d/CentOS-QEMU-EV.repo;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
  sudo yum repolist;
  sudo yum update -y

