release: liberty
undercloud_image_url: http://images.rdoproject.org/liberty/delorean/consistent/stable/undercloud.qcow2
overcloud_image_url: http://images.rdoproject.org/liberty/delorean/consistent/stable/overcloud-full.tar
ipa_image_url: http://images.rdoproject.org/liberty/delorean/consistent/stable/ironic-python-agent.tar
