release: master
undercloud_image_url: http://66.187.229.99/builds/current-tripleo/instack.qcow2
overcloud_image_url: http://66.187.229.99/builds/current-tripleo/overcloud-full.tar
ipa_image_url: http://66.187.229.99/builds/current-tripleo/ipa_images.tar
