devmode: true
overcloud_as_undercloud: true
images:
    - name: overcloud-full
      url: "{{ overcloud_image_url }}"
      type: tar
    - name: ipa_images
      url: "{{ ipa_image_url }}"
      type: tar
inject_images:
    - "ironic-python-agent.initramfs"
    - "ironic-python-agent.vmlinuz"
    - "ironic-python-agent.kernel"
    - "overcloud-full.qcow2"
    - "overcloud-full.initrd"
    - "overcloud-full.vmlinuz"
release: master
overcloud_image_url: http://66.187.229.139/builds/current-tripleo/overcloud-full.tar
ipa_image_url: http://66.187.229.139/builds/current-tripleo/ipa_images.tar
