release: newton
undercloud_image_url: https://images.rdoproject.org/newton/delorean/consistent/stable/undercloud.qcow2
overcloud_image_url: http://images.rdoproject.org/newton/delorean/consistent/stable/overcloud-full.tar
ipa_image_url: http://images.rdoproject.org/newton/delorean/consistent/stable/ironic-python-agent.tar

# release specific ansible variables

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: True
