packaging_script: package-images
working_dir: /home/stack
undercloud_base: undercloud-base.qcow2
virt_customize_base_command: "virt-customize -m 16042 --smp 4 -a {{ working_dir }}/{{ undercloud_base }} --upload"
image_types:
  - ironic-python-agent
  - deploy-ramdisk-ironic
  - overcloud-full
overcloud_images:
  - deploy-ramdisk-ironic.initramfs
  - deploy-ramdisk-ironic.kernel
  - ironic-python-agent.initramfs
  - ironic-python-agent.kernel
  - overcloud-full.initrd
  - overcloud-full.qcow2
  - overcloud-full.vmlinuz