non_root_user: stack
working_dir: "/home/{{ non_root_user }}/.quickstart"
url: https://ci.centos.org/artifacts/rdo/images/liberty/delorean/stable/undercloud.qcow2
pub_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
virt_power_key: /root/.ssh/id_rsa_virt_power
virt_power_user: root
nova_power_manager: 'nova.virt.baremetal.virtual_power_driver.VirtualPowerManager'
ansible_private_key_file: "{{ ansible_ssh_private_key_file }}"
local_working_dir: "./"
networks:
  bridges:
    - name: bridget
  external:
    name: external
    port_start: 65435
    port_end: 65535
    bridge: extbr
    ip: 192.168.23.1
    netmask: 255.255.255.0
    dhcp_start: 192.168.23.2
    dhcp_end: 192.168.23.50
vms:
  engine: 'kvm'
  undercloud:
    nodes:
      - name: undercloud
        disk_size: '50'
        memory: '12288'
        cpus: '3'
    arch: 'x86_64'
    bootdev: 'hd'
  overcloud:
    arch: 'x86_64'
    bootdev: 'network'
    nodes:
      - name: control_0
        disk_size: '50'
        memory: '4096'
        cpus: '1'
        profile: control
      - name: control_1
        disk_size: '50'
        memory: '4096'
        cpus: '1'
        profile: control
      - name: control_2
        disk_size: '50'
        memory: '4096'
        cpus: '1'
        profile: control
      - name: compute_0
        disk_size: '50'
        memory: '4096'
        cpus: '1'
        profile: compute
      - name: ceph_0
        disk_size: '50'
        memory: '4096'
        cpus: '1'
        profile: ceph
  volume_path: /var/lib/libvirt/images/
  volume_pool: default
  diskbus: 'sata'