release: ocata
dlrn_hash: rdo-trunk-ocata-tested
undercloud_image_url: http://images.rdoproject.org/ocata/rdo_trunk/current-tripleo/stable/undercloud.qcow2
overcloud_image_url: http://images.rdoproject.org/ocata/rdo_trunk/current-tripleo/stable/overcloud-full.tar
ipa_image_url: http://images.rdoproject.org/ocata/rdo_trunk/current-tripleo/stable/ironic-python-agent.tar
repos:
  - type: generic
    reponame: delorean
    filename: delorean.repo
    baseurl: https://trunk.rdoproject.org/centos7-ocata/{{ dlrn_hash }}/
    priority: 20

  - type: file
    filename: delorean-deps.repo
    down_url: https://trunk.rdoproject.org/centos7-ocata/delorean-deps.repo

  - type: package
    pkg_name: centos-release-ceph-jewel
    custom_cmd: 'sudo yum install -y --enablerepo=extras'

repo_cmd_after: |
  sudo yum-config-manager --save --setopt centos-ceph-jewel.gpgcheck=0
  sudo yum repolist;
  sudo yum update -y

