# Define a single controller node
overcloud_nodes:
  - name: control_0
    flavor: control

node_count: 1

deployed_server_overcloud_roles:
  - name: Controller
    hosts: "$(sed -n 1,1p /etc/nodepool/sub_nodes_private)"

topology: >-
  --compute-scale 0

