---
- name: Add virthost to inventory
  hosts: localhost
  roles:
    - provision/local

- name: Rebuild inventory
  hosts: localhost
  roles:
    - rebuild-inventory

- name:  Setup the virthost to build images then build them
  hosts: virthost
  gather_facts: yes
  roles:
    - images/build

- name: Publish Images
  hosts: virthost
  gather_facts: no
  roles:
    - { role: "images/publish", when: "publish" }
