---
- include: provision.yml

- name:  Setup the virthost to build images then build them
  hosts: host0
  gather_facts: yes
  roles:
    - libvirt
    - libvirt/setup
    - images/build

- name: Publish Images
  hosts: host0
  gather_facts: no
  roles:
    - { role: "images/publish", when: "publish" }
