---
- name:  Setup undercloud and baremetal vms and networks in libvirt
  hosts: virthost
  gather_facts: yes
  roles:
    - libvirt/setup

- name: Rebuild inventory
  hosts: localhost
  gather_facts: no
  roles:
    - rebuild-inventory
