---
- name:  Setup undercloud and baremetal vms and networks in libvirt
  hosts: virthost
  gather_facts: no
  roles:
    - libvirt/setup

- name: Rebuild inventory
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python"
  roles:
    - rebuild-inventory
