# This playbooks is responsible for preparing a target host.
#
# We start by creating an inventory entry for the target host.
- name: Add virthost to inventory
  hosts: localhost
  roles:
    - provision/local
  tags:
    - provision

# Next, we create a non-root user on the remote system.
- name: Create target user on virt host
  hosts: virthost
  roles:
    - provision/remote
  tags:
    - provision

# Regenerate the inventory file for use in subsequent
# `ansible-playbook` runs.
- name: Rebuild inventory
  hosts: localhost
  roles:
    - rebuild-inventory
  tags:
    - provision

# We need to rerun setup to prevent any possible invalid fact on
# virthost
- name: Run setup again on virthost
  hosts: virthost
  tasks:
    - setup:

