---
- name: Add virthost to inventory
  hosts: localhost
  gather_facts: no
  roles:
    - provision/manual
    - rebuild-inventory

- name:  Setup undercloud and baremetal vms and networks in libvirt
  hosts: virthost
  gather_facts: no
  roles:
    - libvirt/teardown
    - libvirt/setup

- name: Rebuild inventory
  hosts: localhost
  gather_facts: no
  roles:
    - rebuild-inventory
