---
- include: provision.yml
  tags:
    - provision

- name: Install libvirt packages and configure networks
  hosts: virthost
  tags:
    - environment
  roles:
    - environment/setup

- name:  Setup undercloud and baremetal vms and networks in libvirt
  hosts: virthost
  gather_facts: yes
  roles:
    - libvirt/teardown
    - libvirt/setup

# This adds the undercloud node to the generated 
# inventory.
- name: Rebuild inventory
  hosts: localhost
  roles:
    - rebuild-inventory

- name:  Install undercloud and deploy overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo/undercloud
    - tripleo/overcloud
