---
- name: Add virthost to inventory
  hosts: localhost
  gather_facts: no
  roles:
    - provision/manual

- name: Rebuild inventory
  hosts: localhost
  gather_facts: no
  roles:
    - rebuild-inventory

- name:  Teardown previous libvirt setup
  hosts: virthost
  gather_facts: no
  roles:
    - libvirt/teardown

- name:  Setup undercloud and baremetal vms and networks in libvirt
  hosts: virthost
  gather_facts: no
  roles:
    - libvirt/setup