- name:  Setup undercloud and baremetal vms and networks in libvirt
  hosts: host0
  gather_facts: no
  vars:
    url: "http://artifacts.ci.centos.org/artifacts/rdo/images/mitaka/delorean/testing/undercloud.qcow2"
    local_working_dir: "{{ lookup('env', 'WORKSPACE') }}/khaleesi"
  roles:
    - libvirt/setup

- name: Rebuild inventory
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python"
    local_working_dir: "{{ lookup('env', 'WORKSPACE') }}/khaleesi"
  roles:
    - rebuild-inventory

- name:  Install undercloud and deploy overcloud
  hosts: undercloud
  gather_facts: no
  vars:
    local_working_dir: "{{ lookup('env', 'WORKSPACE') }}/khaleesi"
    create_flavors: false
    extra_args: "--control-scale 3 -e /usr/share/openstack-tripleo-heat-templates/environments/puppet-pacemaker.yaml --ntp-server pool.ntp.org"
    tempest: false
    pingtest: true
    bash_deploy_ramdisk: false
    release: mitaka
  roles:
    - overcloud