- name: Create env-setup script
  template:
    src: "{{ env_setup_script }}"
    dest: "{{ working_dir }}"
    mode: 0744

- name: create libvirtd group
  group:
    name: libvirtd
    state: present

- name: Run the env-setup script
  shell: "{{ working_dir }}/{{ env_setup_script }}"

- name: start libvirtd
  service:
    name: libvirtd
    state: running

- name: ensure correct permissions on /dev/kvm
  file:
    path: /dev/kvm
    owner: root
    group: kvm
    mode: 0664
